module.exports = {
  CREDIT: 'CREDIT',
  DEBIT: 'DEBIT',

  SOURCES: {
    SPIN: 'SPIN',
    REFERRAL: 'REFERRAL',
    CASHBACK: 'CASHBACK',
    SUBSCRIPTION: 'SUBSCRIPTION',
    MANUAL: 'MANUAL',
    SPEND: 'SPEND'
    AFFILIATE: 'AFFILIATE', // ✅ ADD THIS
    AFFILIATE_MATURED: 'AFFILIATE_MATURED' // ✅ ADD THIS
  },

  WALLET_STATUS: {
    ACTIVE: 'active',
    FROZEN: 'frozen'
  }
};

